### ISSUE TITLE
MQTT for EVSE-WIFI

### ISSUE THREAD

**Issue by roesl** [CurtRod/SimpleEVSE-WiFi#25]
Is it possible to add MQTT feature to Control the EVSA wit MQTT commands ?

Georg

**Comment by s0170071** [comment]
+1 from me. 
I do already have the mains power readings and solar power readings in my OpenHab installation.   
I would like either
a) communicate these power readings to EVSE so it can use it for solar charging
b) control power output of EVSE myself (based on my readings)
MQTT style is very much appreachiated.

**Comment by neographikal** [comment]
+1

This would make it much more versatile!

**Comment by alx2k** [comment]
@neographikal, It would be much more versatile, but it is not needed.

I have "home assistant" at home, and a wemosEM power meter (also on github). When my home consumption changes in 1 Amp, home assistant sends a http request to the charger using "http://192.168.4.1/setCurrent?current=XXXX". It works flawlessly.

@s0170071, If you want, I can send you my home assistant configuration, maybe it is similar in Openhab.

**Comment by neographikal** [comment]
I can get it to work, but MQTT is much more versatile, reliable and almost everything I use is connected through MQTT. Especially when it's a ESP32/8266 (Tasmota/esphomelib), for some stuff I even wrapped the existing API for MQTT with Nodered.

Thanks for the suggestion but this still would be important to me :)

**Comment by spoeh-man** [comment]
+1 for me is also better with mqtt for iobroker

**Comment by njordan77** [comment]
i would also love to see your great project compatible with MQTT (pubsubclient, rather easy to handle)

**Comment by kolaCZek** [comment]
+1 Do want!!!

**Comment by krispek** [comment]
+1 for me. The HA-solution works, but MQTT would make it even better. :)

**Comment by captain186** [comment]
> If you want, I can send you my home assistant configuration, maybe it is similar in Openhab.

Hi, I'm intrested in using evse-with home assistant. Could you send me your configuration, please?
Thanks a lot in advance!

**Comment by kolaCZek** [comment]
```
rest_command:
  evse_enable:
    url: 'http://192.168.0.140/setCurrent?current=13'
  evse_disable:
    url: 'http://192.168.0.140/setCurrent?current=0'

switch:
  - platform: template
    switches:
      wifi_evse:
        value_template: "{{ is_state('sensor.wifi_evse', '13') }}"
        turn_on:
          service: rest_command.evse_enable
        turn_off:
          service: rest_command.evse_disable
```
